/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmicalculator;

import classBMICalculator.User;

/**
 *
 * @author Andreas Bayu P
 */
public class BMIMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form BMIMainForm
     */
    User accountAktif;
    
    public BMIMainFrame() {
        initComponents();
    }

    public BMIMainFrame(User account) {
        initComponents();    
        accountAktif = new User();
        accountAktif = account;
        labelSelamatDatang.setText("Selamat datang, " + accountAktif.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelamatDatang = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JAccount = new javax.swing.JMenu();
        jHistory = new javax.swing.JMenuItem();
        jOperation = new javax.swing.JMenu();
        jBMI = new javax.swing.JMenuItem();
        jGraph = new javax.swing.JMenuItem();
        jExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSelamatDatang.setText("Selamat datang, nama");

        JAccount.setText("Account");

        jHistory.setText("History");
        jHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHistoryActionPerformed(evt);
            }
        });
        JAccount.add(jHistory);

        jMenuBar1.add(JAccount);

        jOperation.setText("Operation");

        jBMI.setText("Calculate BMI");
        jBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMIActionPerformed(evt);
            }
        });
        jOperation.add(jBMI);

        jGraph.setText("My Graph");
        jGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGraphActionPerformed(evt);
            }
        });
        jOperation.add(jGraph);

        jMenuBar1.add(jOperation);

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(jExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSelamatDatang)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSelamatDatang)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHistoryActionPerformed
        BMIHistoryFrame formHistory = new BMIHistoryFrame(accountAktif);
        formHistory.setVisible(true);
    }//GEN-LAST:event_jHistoryActionPerformed

    private void jBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMIActionPerformed
        BMICalculatorFrame formCalc = new BMICalculatorFrame(accountAktif);
        formCalc.setVisible(true);
    }//GEN-LAST:event_jBMIActionPerformed

    private void jGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGraphActionPerformed
        BMIGraphicFrame formGraph = new BMIGraphicFrame(accountAktif);
        formGraph.setVisible(true);
    }//GEN-LAST:event_jGraphActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JAccount;
    private javax.swing.JMenuItem jBMI;
    private javax.swing.JMenu jExit;
    private javax.swing.JMenuItem jGraph;
    private javax.swing.JMenuItem jHistory;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jOperation;
    private javax.swing.JLabel labelSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
